version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./web:/var/www
    restart: always
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    container_name: nginx
    working_dir: /var/www/
    volumes_from:
      - app
    restart: always
    ports:
      - 8080:80
   

  # The Database
  database:
    image: mysql:5.6
    container_name: mysql
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_ROOT_USER=root"
    restart: always
    ports:
        - "33061:3306"

# phpmyadmin
  myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        restart: always
        depends_on:
            - database
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
  
